[package]
name = "zoneinfo_parse"
description = "Library for parsing zoneinfo time zone files"

authors = ["Ben S <ogham@bsago.me>"]
documentation = "https://docs.rs/zoneinfo_parse"
exclude = ["/README.md", "/LICENCE", "/.rustfmt.toml", "/.travis.yml"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rust-datetime/zoneinfo-compiled"
version = "0.1.4"

[dependencies]
datetime = "0.4.4"
lazy_static = "0.2.1"
regex = "0.1.77"
